package com.macamara.app;
import android.app.*;import android.content.*;import android.os.*;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.video.*;import androidx.core.app.NotificationCompat;import androidx.core.content.ContextCompat;import androidx.lifecycle.LifecycleService;import com.google.common.util.concurrent.ListenableFuture;import java.io.File;import java.util.concurrent.*;
public class RecordingService extends LifecycleService{
 public static final String ACTION_START="com.macamara.START",ACTION_STOP="com.macamara.STOP";public static volatile boolean isRecording=false;public static volatile String currentSegmentName="none";final Handler h=new Handler(Looper.getMainLooper());final ExecutorService ex=Executors.newSingleThreadExecutor();Recording recording;Recorder recorder;VideoCapture<Recorder> capture;boolean stopping;long segmentStart;long segmentId;MemoryStore db;
 public void onCreate(){super.onCreate();db=new MemoryStore(this);channel();}
 public int onStartCommand(Intent i,int f,int id){super.onStartCommand(i,f,id);if(i!=null&&ACTION_STOP.equals(i.getAction())){stopping=true;isRecording=false;stopClip();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();}else if(i!=null&&ACTION_START.equals(i.getAction())&&!isRecording){stopping=false;startForeground(17,notification());camera();}return START_STICKY;}
 void camera(){ListenableFuture<ProcessCameraProvider> fu=ProcessCameraProvider.getInstance(this);fu.addListener(()->{try{ProcessCameraProvider p=fu.get();p.unbindAll();recorder=new Recorder.Builder().setQualitySelector(QualitySelector.from(Quality.FHD)).build();capture=VideoCapture.withOutput(recorder);p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,capture);startClip();}catch(Exception e){isRecording=false;stopSelf();}},ContextCompat.getMainExecutor(this));}
 void startClip(){if(stopping||capture==null)return;File d=new File(getExternalFilesDir(null),"Memory");d.mkdirs();File file=new File(d,"MEMORY_"+System.currentTimeMillis()+".mp4");currentSegmentName=file.getName();segmentStart=System.currentTimeMillis();FileOutputOptions out=new FileOutputOptions.Builder(file).build();recording=recorder.prepareRecording(this,out).withAudioEnabled().start(ContextCompat.getMainExecutor(this),e->{if(e instanceof VideoRecordEvent.Finalize){VideoRecordEvent.Finalize x=(VideoRecordEvent.Finalize)e;long end=System.currentTimeMillis();Recording old=recording;recording=null;if(x.getError()==VideoRecordEvent.Finalize.ERROR_NONE&&!stopping){long cid=db.addClip(file.getAbsolutePath(),segmentStart,end);ClipAnalyzer.analyze(this,cid,file,db);h.postDelayed(this::startClip,250);}}});isRecording=true;h.postDelayed(()->{if(!stopping&&recording!=null){Recording r=recording;recording=null;r.stop();}},120000);}
 void stopClip(){h.removeCallbacksAndMessages(null);if(recording!=null){Recording r=recording;recording=null;r.stop();}}
 Notification notification(){return new NotificationCompat.Builder(this,"mc").setSmallIcon(android.R.drawable.ic_menu_camera).setContentTitle("MA CAMARA").setContentText("Visible memory recording is active").setOngoing(true).setCategory(NotificationCompat.CATEGORY_SERVICE).build();}
 void channel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel("mc","MA CAMARA recording",NotificationManager.IMPORTANCE_LOW));}
 public void onDestroy(){stopping=true;isRecording=false;stopClip();ex.shutdownNow();super.onDestroy();}
}